# Generated by Django 5.0 on 2026-03-26 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0002_user_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='requested_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
