# Generated by Django 5.0 on 2026-04-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0006_brand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_brand',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
