# Generated by Django 5.0 on 2026-04-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0009_brand_created_at_brand_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='custom_brand',
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.CharField(blank=True, choices=[('attacker', 'Attacker'), ('midfielder', 'Midfielder'), ('defender', 'Defender'), ('goalkeeper', 'Goalkeeper')], max_length=20, null=True),
        ),
    ]
