# Generated by Django 5.0 on 2026-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0011_productimage_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kits', 'Jersey & Kits'), ('boots', 'Football Boots'), ('accessories', 'Accessories (Socks, Guards)'), ('equipment', 'Training Equipment (Balls, Cones)'), ('supplements', 'Health & Supplements')], default='kits', max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
