# Generated by Django 5.0 on 2026-04-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0012_alter_product_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='boot_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='kit_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kits', 'Jersey & Kits'), ('boots', 'Football Boots'), ('accessories', 'Accessories'), ('equipment', 'Training Equipment'), ('supplements', 'Health & Supplements')], max_length=20),
        ),
    ]
