# Generated by Django 5.0 on 2026-04-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0013_product_boot_size_product_kit_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kit_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=20, null=True),
        ),
    ]
