# Generated by Django 5.0 on 2026-04-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0014_alter_product_kit_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
