# Generated by Django 5.0 on 2026-04-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0015_orderitem_dispatched'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='received_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
