# Generated by Django 5.0 on 2026-04-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0016_orderitem_received_by_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='received_by_admin',
            new_name='received',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid (Held by Admin)'), ('shipping', 'Shipping in Progress'), ('shipped', 'Shipped'), ('completed', 'Delivered & Received'), ('cancelled', 'Cancelled')], default='paid', max_length=20),
        ),
    ]
