# Generated by Django 5.0 on 2026-05-06 02:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0017_rename_received_by_admin_orderitem_received_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='disbursement',
            unique_together={('order', 'vendor')},
        ),
        migrations.AddField(
            model_name='disbursement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='as_app.order'),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='disbursement',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='as_app.vendor'),
        ),
        migrations.RemoveField(
            model_name='disbursement',
            name='admin_commission',
        ),
    ]
