# Generated by Django 5.0 on 2026-05-06 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0018_alter_disbursement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
