# Generated by Django 5.0 on 2026-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('as_app', '0019_disbursement_admin_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('esewa', 'eSewa'), ('cod', 'Cash on Delivery')], default='esewa', max_length=20),
        ),
    ]
